In [3]:
import pandas as pd

# DATA LOAD AND BASIC DATA EXPLORATION

In [4]:
df_HR = pd.read_csv('HR_Analytics.csv')
df_HR.head()

,EmpID,Age,AgeGroup,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,RM297,18,18-25,Yes,Travel_Rarely,230,Research & Development,3,3,Life Sciences,...,3,80,0,0,2,3,0,0,0,0.0
1,RM302,18,18-25,No,Travel_Rarely,812,Sales,10,3,Medical,...,1,80,0,0,2,3,0,0,0,0.0
2,RM458,18,18-25,Yes,Travel_Frequently,1306,Sales,5,3,Marketing,...,4,80,0,0,3,3,0,0,0,0.0
3,RM728,18,18-25,No,Non-Travel,287,Research & Development,5,2,Life Sciences,...,4,80,0,0,2,3,0,0,0,0.0
4,RM829,18,18-25,Yes,Non-Travel,247,Research & Development,8,1,Medical,...,4,80,0,0,0,3,0,0,0,0.0

In [5]:
df_HR.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1480 entries, 0 to 1479
Data columns (total 38 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   EmpID                     1480 non-null   object
 1   Age                       1480 non-null   int64
 2   AgeGroup                  1480 non-null   object
 3   Attrition                 1480 non-null   object
 4   BusinessTravel            1480 non-null   object
 5   DailyRate                 1480 non-null   int64
 6   Department                1480 non-null   object
 7   DistanceFromHome          1480 non-null   int64
 8   Education                 1480 non-null   int64
 9   EducationField            1480 non-null   object
 10  EmployeeCount             1480 non-null   int64
 11  EmployeeNumber            1480 non-null   int64
 12  EnvironmentSatisfaction   1480 non-null   int64
 13  Gender                    1480 non-null   object
 14  HourlyRate                1480 non-null   int64
 15  JobInvolvement            1480 non-null   int64
 16  JobLevel                  1480 non-null   int64
 17  JobRole                   1480 non-null   object
 18  JobSatisfaction           1480 non-null   int64
 19  MaritalStatus             1480 non-null   object
 20  MonthlyIncome             1480 non-null   int64
 21  SalarySlab                1480 non-null   object
 22  MonthlyRate               1480 non-null   int64
 23  NumCompaniesWorked        1480 non-null   int64
 24  Over18                    1480 non-null   object
 25  OverTime                  1480 non-null   object
 26  PercentSalaryHike         1480 non-null   int64
 27  PerformanceRating         1480 non-null   int64
 28  RelationshipSatisfaction  1480 non-null   int64
 29  StandardHours             1480 non-null   int64
 30  StockOptionLevel          1480 non-null   int64
 31  TotalWorkingYears         1480 non-null   int64
 32  TrainingTimesLastYear     1480 non-null   int64
 33  WorkLifeBalance           1480 non-null   int64
 34  YearsAtCompany            1480 non-null   int64
 35  YearsInCurrentRole        1480 non-null   int64
 36  YearsSinceLastPromotion   1480 non-null   int64
 37  YearsWithCurrManager      1423 non-null   float64
dtypes: float64(1), int64(25), object(12)
memory usage: 439.5+ KB

# CHECK AND DROP NULL VALUES

In [6]:
df_HR.isnull().sum()

EmpID                        0
Age                          0
AgeGroup                     0
Attrition                    0
BusinessTravel               0
DailyRate                    0
Department                   0
DistanceFromHome             0
Education                    0
EducationField               0
EmployeeCount                0
EmployeeNumber               0
EnvironmentSatisfaction      0
Gender                       0
HourlyRate                   0
JobInvolvement               0
JobLevel                     0
JobRole                      0
JobSatisfaction              0
MaritalStatus                0
MonthlyIncome                0
SalarySlab                   0
MonthlyRate                  0
NumCompaniesWorked           0
Over18                       0
OverTime                     0
PercentSalaryHike            0
PerformanceRating            0
RelationshipSatisfaction     0
StandardHours                0
StockOptionLevel             0
TotalWorkingYears            0
TrainingTimesLastYear        0
WorkLifeBalance              0
YearsAtCompany               0
YearsInCurrentRole           0
YearsSinceLastPromotion      0
YearsWithCurrManager        57
dtype: int64

In [7]:
# drop column with null values 
df_HR_cleaned = df_HR.dropna(axis=1) # drop columns with any null values
df_HR_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1480 entries, 0 to 1479
Data columns (total 37 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   EmpID                     1480 non-null   object
 1   Age                       1480 non-null   int64
 2   AgeGroup                  1480 non-null   object
 3   Attrition                 1480 non-null   object
 4   BusinessTravel            1480 non-null   object
 5   DailyRate                 1480 non-null   int64
 6   Department                1480 non-null   object
 7   DistanceFromHome          1480 non-null   int64
 8   Education                 1480 non-null   int64
 9   EducationField            1480 non-null   object
 10  EmployeeCount             1480 non-null   int64
 11  EmployeeNumber            1480 non-null   int64
 12  EnvironmentSatisfaction   1480 non-null   int64
 13  Gender                    1480 non-null   object
 14  HourlyRate                1480 non-null   int64
 15  JobInvolvement            1480 non-null   int64
 16  JobLevel                  1480 non-null   int64
 17  JobRole                   1480 non-null   object
 18  JobSatisfaction           1480 non-null   int64
 19  MaritalStatus             1480 non-null   object
 20  MonthlyIncome             1480 non-null   int64
 21  SalarySlab                1480 non-null   object
 22  MonthlyRate               1480 non-null   int64
 23  NumCompaniesWorked        1480 non-null   int64
 24  Over18                    1480 non-null   object
 25  OverTime                  1480 non-null   object
 26  PercentSalaryHike         1480 non-null   int64
 27  PerformanceRating         1480 non-null   int64
 28  RelationshipSatisfaction  1480 non-null   int64
 29  StandardHours             1480 non-null   int64
 30  StockOptionLevel          1480 non-null   int64
 31  TotalWorkingYears         1480 non-null   int64
 32  TrainingTimesLastYear     1480 non-null   int64
 33  WorkLifeBalance           1480 non-null   int64
 34  YearsAtCompany            1480 non-null   int64
 35  YearsInCurrentRole        1480 non-null   int64
 36  YearsSinceLastPromotion   1480 non-null   int64
dtypes: int64(25), object(12)
memory usage: 427.9+ KB

# CLEANED DATASET

In [8]:
df_HR_cleaned.isnull().sum()

EmpID                       0
Age                         0
AgeGroup                    0
Attrition                   0
BusinessTravel              0
DailyRate                   0
Department                  0
DistanceFromHome            0
Education                   0
EducationField              0
EmployeeCount               0
EmployeeNumber              0
EnvironmentSatisfaction     0
Gender                      0
HourlyRate                  0
JobInvolvement              0
JobLevel                    0
JobRole                     0
JobSatisfaction             0
MaritalStatus               0
MonthlyIncome               0
SalarySlab                  0
MonthlyRate                 0
NumCompaniesWorked          0
Over18                      0
OverTime                    0
PercentSalaryHike           0
PerformanceRating           0
RelationshipSatisfaction    0
StandardHours               0
StockOptionLevel            0
TotalWorkingYears           0
TrainingTimesLastYear       0
WorkLifeBalance             0
YearsAtCompany              0
YearsInCurrentRole          0
YearsSinceLastPromotion     0
dtype: int64

In [9]:
df_HR_cleaned.value_counts()

EmpID   Age  AgeGroup  Attrition  BusinessTravel     DailyRate  Department              DistanceFromHome  Education  EducationField  EmployeeCount  EmployeeNumber  EnvironmentSatisfaction  Gender  HourlyRate  JobInvolvement  JobLevel  JobRole                    JobSatisfaction  MaritalStatus  MonthlyIncome  SalarySlab  MonthlyRate  NumCompaniesWorked  Over18  OverTime  PercentSalaryHike  PerformanceRating  RelationshipSatisfaction  StandardHours  StockOptionLevel  TotalWorkingYears  TrainingTimesLastYear  WorkLifeBalance  YearsAtCompany  YearsInCurrentRole  YearsSinceLastPromotion
RM1464  31   26-35     No         Non-Travel         325        Research & Development  5                 3          Medical         1              2057            2                        Male    74          3               2         Manufacturing Director     1                Single         9936           5k-10k      3787         0                   Y       No        19                 3                  2                         80             0                 10                 2                      3                9               4                   1                          2
RM1465  26   26-35     No         Travel_Rarely      1167       Sales                   5                 3          Other           1              2060            4                        Female  30          2               1         Sales Representative       3                Single         2966           Upto 5k     21378        0                   Y       No        18                 3                  4                         80             0                 5                  2                      3                4               2                   0                          2
RM1466  36   36-45     No         Travel_Frequently  884        Research & Development  23                2          Medical         1              2061            3                        Male    41          4               2         Laboratory Technician      4                Married        2571           Upto 5k     12290        4                   Y       No        17                 3                  3                         80             1                 17                 3                      3                5               2                   0                          2
RM1467  39   36-45     No         Travel_Rarely      613        Research & Development  6                 1          Medical         1              2062            4                        Male    42          2               3         Healthcare Representative  1                Married        9991           5k-10k      21457        4                   Y       No        15                 3                  1                         80             1                 9                  5                      3                7               7                   1                          2
RM1468  27   26-35     No         Travel_Rarely      155        Research & Development  4                 3          Life Sciences   1              2064            2                        Male    87          4               2         Manufacturing Director     2                Married        6142           5k-10k      5174         1                   Y       Yes       20                 4                  2                         80             1                 6                  0                      3                6               2                   0                          2
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ..
RM979   40   36-45     No         Travel_Rarely      1202       Research & Development  2                 1          Medical         1              1375            2                        Female  89          4               2         Healthcare Representative  3                Divorced       6377           5k-10k      13888        5                   Y       No        20                 4                  2                         80             3                 15                 0                      3                12              11                  11                         1
RM980   34   26-35     No         Travel_Rarely      285        Research & Development  29                3          Medical         1              1377            2                        Male    86          3               2         Laboratory Technician      3                Married        5429           5k-10k      17491        4                   Y       No        13                 3                  1                         80             2                 10                 1                      3                8               7                   7                          1
RM981   31   26-35     Yes        Travel_Frequently  703        Sales                   2                 3          Life Sciences   1              1379            3                        Female  90          2               1         Sales Representative       4                Single         2785           Upto 5k     11882        7                   Y       No        14                 3                  3                         80             0                 3                  3                      4                1               0                   0                          1
RM982   35   26-35     Yes        Travel_Frequently  662        Sales                   18                4          Marketing       1              1380            4                        Female  67          3               2         Sales Executive            3                Married        4614           Upto 5k     23288        0                   Y       Yes       18                 3                  3                         80             1                 5                  0                      2                4               2                   3                          1
RM999   26   26-35     No         Travel_Rarely      683        Research & Development  2                 1          Medical         1              1407            1                        Male    36          2               1         Research Scientist         4                Single         3904           Upto 5k     4050         0                   Y       No        12                 3                  4                         80             0                 5                  2                      3                4               3                   1                          1
Name: count, Length: 1470, dtype: int64

In [10]:
df_HR_cleaned

,EmpID,Age,AgeGroup,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,...,PerformanceRating,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion
0,RM297,18,18-25,Yes,Travel_Rarely,230,Research & Development,3,3,Life Sciences,...,3,3,80,0,0,2,3,0,0,0
1,RM302,18,18-25,No,Travel_Rarely,812,Sales,10,3,Medical,...,3,1,80,0,0,2,3,0,0,0
2,RM458,18,18-25,Yes,Travel_Frequently,1306,Sales,5,3,Marketing,...,3,4,80,0,0,3,3,0,0,0
3,RM728,18,18-25,No,Non-Travel,287,Research & Development,5,2,Life Sciences,...,3,4,80,0,0,2,3,0,0,0
4,RM829,18,18-25,Yes,Non-Travel,247,Research & Development,8,1,Medical,...,3,4,80,0,0,0,3,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1475,RM412,60,55+,No,Travel_Rarely,422,Research & Development,7,3,Life Sciences,...,3,4,80,0,33,5,1,29,8,11
1476,RM428,60,55+,No,Travel_Frequently,1499,Sales,28,3,Marketing,...,3,4,80,0,22,5,4,18,13,13
1477,RM537,60,55+,No,Travel_Rarely,1179,Sales,16,4,Marketing,...,3,4,80,0,10,1,3,2,2,2
1478,RM880,60,55+,No,Travel_Rarely,696,Sales,7,4,Marketing,...,3,2,80,1,12,3,3,11,7,1
1479,RM1210,60,55+,No,Travel_Rarely,370,Research & Development,1,4,Medical,...,4,3,80,1,19,2,4,1,0,0

# LOAD DATA TO A NEW CSV

In [11]:
df_HR_cleaned.to_csv('df_HRanalyticsCleaned.csv', index=False) 
# save cleaned data to new CSV file with index false means we don't want to save the index column